### ISSUE TITLE
NH600D listed with USB ID of 0187

### ISSUE THREAD

**Issue by DrSheep** [cybercase/netmd-js#15]
Just got a NH600D for testing, and somehow it has an ID of 0187 (as reported by Zadig), which is not 0186 as listed within netmd.ts.  Much appreciated if you can look into this.

**Comment by cybercase** [comment]
@DrSheep Thanks for reporting this. I'll add your id to `netmd.ts` and update the package.

**Comment by DrSheep** [comment]
Not sure why, but I am still getting access denied or "The requested
interface implements a protected class." error.

Thanks.

**Comment by cybercase** [comment]
It could be related to the mode setting on your device. hi-md mode is not supported, so you might want to set your device to standard mode

**Comment by DrSheep** [comment]
Interesting.  I just switched to MD mode and the hardware id comes up
as 0186.  So I guess 0187 is for Hi-MD mode for the NH600D.

p.s. any chance for Hi-MD support?

**Comment by cybercase** [comment]
In theory we could add support for hi-md, however, for security reasons Chrome does not allow accessing hi-md devices via the WebUSB protocol (that's the cause of `The requested interface implements a protected class` error you've got)

This means that hi-md support could work only in node, and not in the browser.

**Comment by DrSheep** [comment]
Thanks for getting back to me and letting me know.
