### ISSUE TITLE
Some NetMD devices are missing

### ISSUE THREAD

**Issue by Invictaz** [cybercase/netmd-js#2]
Seeing this page:

https://github.com/cybercase/netmd-js/blob/master/src/netmd.ts

Some NetMD devices are missing

je780
s500
nt1
se9

see this page:

https://www.minidisc.org/part_Decks_Sony.html

**Comment by cybercase** [comment]
I'll try to bring in all the devices listed here: https://github.com/linux-minidisc/linux-minidisc/blob/fdfec4f8ce0406c44e3ec21ff6685b82072987a1/libnetmd/netmd_dev.c

Can't do much for the devices that aren't in the list as I don't have vendor and device IDs.

**Comment by Invictaz** [comment]
At least that covers JE780. Probably more are missing, I only checked Sony NetMD decks.
