### ISSUE TITLE
Add Kenwood MDX-J9 to the list?

### ISSUE THREAD

**Issue by suppinPUB** [cybercase/netmd-js#22]
Hi can you add the Kenwood MDX-J9 to the netmd.ts
Here is the PID and VID

Device Address : 5
Manufacturer : Kenwood Corp.
Device Name : Net MD 
Vendor Id : 2856 
Product Id : 4100

Those are from Platinum MD.  from the Google Device Log it loks like this

USB device added: path=\\?\usb#vid_0b28&pid_1004#6&2b607cbb&0&1#{a5dcbf10-6530-11d2-901f-00c04fb951ed} vendor=2856 "KENWOOD ", product=4100 "Net MD ", serial="", driver="WinUSB", guid=03fa1357-45e6-43be-9195-b74e9f8265f3

**Comment by cybercase** [comment]
Sure, I'll do it!

**Comment by cybercase** [comment]
@suppinPUB I've added the new vendor & device Ids, and updated the Web MiniDisc app to use the updated version of netmd-js. Let me know if it works fine for you.

Keep in mind that you might need to open the Web MiniDisc app a couple of times to get the new updated version: just refreshing the page won't do. You'll need to open the app, wait a few seconds for the new version to be ready and then restart the browser or close the tab.

**Comment by suppinPUB** [comment]
Well I see the device on the list now, but it doesn't work (very sad).  I'm going to do some quick debugging
and see where it's complaining...

store.ts:16 Error: Rejected
    at t [as constructor] (netmd-interface.ts:100)
    at new t (netmd-interface.ts:112)
    at e.<anonymous> (netmd-interface.ts:181)
    at 2.26e6516a.chunk.js:2
    at Object.next (2.26e6516a.chunk.js:2)
    at o (2.26e6516a.chunk.js:2)

**Comment by cybercase** [comment]
I'm sorry to hear that. Your best chance for debugging is to use the netmd-js cli, try to run some commands and see what's the line that's causing the Error. Keep in mind that you might need some confidence with node and typescript to do this.

**Comment by suppinPUB** [comment]
Good tips!  I installed the cli.  
I see devices work.
i see status work.
i see it failing on "ls"

NetMDRejected [Error]: Rejected
    at NetMDRejected.NetMDError [as constructor] (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:191:28)
    at new NetMDRejected (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:209:28)
    at NetMDInterface.<anonymous> (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:323:31)
    at step (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:46:23)
    at Object.next (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:27:53)
    at fulfilled (C:\Users\spoon\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:18:58)

Which points to the "getOperatingStatus" function I think.  Not entirely sure what's going on, but I'll examine it more later.  at least I see where the problem is at.

**Comment by suppinPUB** [comment]
Yeah I was way off.  not getOperatingStatus.  the problem appears to be so far in the "list content"
getDiscFlags which is the first call succeeds.   getDiscTitle() fails when trying to send some sort of binary
string  query = query_utils_1.formatQuery('1806 02201801 00%b 3000 0a00 ff00 %w%w', wcharValue, remaining, done);

**Comment by cybercase** [comment]
One easy thing that you could try out, is to play with the default timeouts, here: https://github.com/cybercase/netmd-js/blob/master/src/netmd.ts#L53 and here: https://github.com/cybercase/netmd-js/blob/master/src/netmd-interface.ts#L120

You could try to raise them and see if it has any effect.

**Comment by suppinPUB** [comment]
There does appear to be some kind of race condition occurring. as even getDiscFlags occassionally fails.  I'll examine more tonight.

**Comment by asivery** [comment]
@suppinPUB Would you be interested in checking it again? I managed to add support to a different Kenwood recently, that was throwing a similar error. It was caused by incorrect managing of open / closed descriptors. You should be able to test it out on my fork - [Web Minidisc Pro](https://web.minidisc.wiki) - it's running the latest version of netmd-js.

**Comment by suppinPUB** [comment]
Yes!  I can give it a try this weekend.  I'll report back what I find this weekend.

**Comment by suppinPUB** [comment]
@asivery Web Minidisc Pro works!  I can play, record, and rename tracks using your fork.  Hah i even see "Kenwood MDX-J9" as the detected device.  Very nice!  I wonder how many people actually own this quirky kenwood boombox.  Regardless thanks for your hard work!

**Comment by asivery** [comment]
@suppinPUB Thanks for checking! Glad it works
