### ISSUE TITLE
Add Panasonic SJ-MR250 to netmd.ts

### ISSUE THREAD

**Issue by FlabberQuestion** [cybercase/netmd-js#27]
Hi. Can you add the Panasonic SJ-MR250?

`{ vendorId: 0x04da, deviceId: 0x23b3, name: 'Panasonic SJ-MR250' },`

**Comment by FlabberQuestion** [comment]
Sorry to bother you with yet another stupid question. I wanted to test this change, so I downloaded the code, made changes to the netmd.ts file and ran it locally `netmdcli devices` (I installed node.js etc), but that doesn't seem to work that way? Since I also own a Sharp minidisc that works fine, I changed the name for testing purposes, (I changed DR-400 to DR-410) But running netmdcli devices it still shows the old name? 

I also tried to fork netmd-js and tried it that way but that didn't work either. How can I test this code myself before you make the actual change?

**Comment by FlabberQuestion** [comment]
Ok, last post I think.  I think I managed to get it working with testing with netmdcli

I found out, after my building didn't go as planned, that all the files are lcoated in: `\AppData\Roaming\npm\node_modules\netmd-js\dist\`
I edited the file netmd.js there and added my Panasonic. After that it was successfully detected!

```
\GitHub\netmd-js\dist>netmdcli devices
Found Device: Panasonic SJ-MR250
```

I ran some basic commands, which also seem to work fine:

```
\GitHub\netmd-js\dist>netmdcli status

discPresent: true,
state: 'ready',
track: 0,
time: { minute: 0, second: 0, frame: 0 }
```

And a rename which was successfully written to the TOC!

`\GitHub\netmd-js\dist>netmdcli rename 1 "Web Minidisc rocks!"`

**Comment by cybercase** [comment]
@Stealthius thanks for you testing. I'm adding the new device, then publish a new version of the library, and finally build a new version of WebMiniDisc. I'll let you know when it's ready

**Comment by FlabberQuestion** [comment]
@cybercase Awesome! Thanks so much!

**Comment by FlabberQuestion** [comment]
I was doing some more testing and found out that `netmdcli ls` throws an error:

```
Error: Format and input mismatch at 18: expected 128, got 8
    at Object.scanQuery (\AppData\Roaming\npm\node_modules\netmd-js\dist\query-utils.js:196:27)
    at NetMDInterface.<anonymous> (\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:1164:45)
    at step (\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:46:23)
    at Object.next (\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:27:53)
    at fulfilled (\AppData\Roaming\npm\node_modules\netmd-js\dist\netmd-interface.js:18:58)
```
I am able to send commands with `netmdcli command play` and the player responds to that.

Unfortunately that's as far as my debugging skills go. I don't know if it would throw the same error once it's available in the actual program though.

**Comment by FlabberQuestion** [comment]
Ok, I did some more debugging since i found the netmd_test repository from deenine. These are the results:

```
python netmd_test.py
Found NetMD: Bus 001 Device 029: ID 04da:23b3 Panasonic Net MD
Found 1 netmd_devs
Acquire Device ....OK
Get Status ....OK
Get Disc Flags ....OK
Get Disc Title ....OK
BIB
Get Disc Capacity ....FAIL
Error: Format and input mismatch at 18: expected 80, got 08
Get Track Count ....OK
2 tracks
Get Length track 2 ....OK
Get Encoding Track 2 ....OK
Get Flags Track 2 ....OK
Move Track 1 to Track 2 ....OK
Play ....OK
Skip forward ....OK
Pause ....OK
Play ....OK
Get position ....OK
Stop ....OK
Enter Secure Session ....OK
Get Leaf ID ....OK
Leave Secure Session ....OK
Release Device ....OK
```

**Comment by cybercase** [comment]
@Stealthius I've updated the library and released a new version of web minidisc. Now your device should be recognized. If not, try to close and reopen the browser.

However, the fact that the Get Disc Capacity command is failing, might be a problem for webminidisc to work correctly. Let me know if that's the case.

**Comment by FlabberQuestion** [comment]
@cybercase Thank you for this. Unfortunately it throws an error. The device now gets recognized but I end up with:

![image](https://user-images.githubusercontent.com/94482785/142760514-6af6aef5-3cbb-402e-a675-29d39bc8661b.png)

Which most likely is because of the `Get Disc Capacity` error mentioned earlier. :-(

**Comment by asivery** [comment]
@Stealthius Hi, would you be interested to test it again, on the latest version? I recently managed to add compatibility for the SJ-MR250, and would just like to make sure the error you're having is also gone. You can test it hare: [Web Minidisc Pro](https://web.minidisc.wiki).

**Comment by FlabberQuestion** [comment]
@asivery Hi!! It works! Thanks so much! I tested SP, LP2, LP4, Wiping disc, renaming, change TOC order, and everything seems to work fine. Well done!

**Comment by asivery** [comment]
Great! Thanks for checking @Stealthius !

**Comment by asivery** [comment]
Meant to ping @FlabberQuestion, sorry
