### ISSUE TITLE
Unknown Device for Sony CMT-M333NT/M373NT

### ISSUE THREAD

**Issue by chonkusZZ** [cybercase/netmd-js#28]
Would you be able to add Sony CMT-M333NT/M373NT bookshelf unit for device identification?

`{ vendorId: 0x054c, deviceId: 0x00e7, name: 'Sony CMT-M333NT/M373NT' }`

All functions seem to work fine on this unit so I don't think anything else is needed.
Thanks for your great work on this project.

**Comment by asivery** [comment]
@chonkusZZ Added in 3.2.1
