### ISSUE TITLE
Will there be support to decrypt OMG files?

### ISSUE THREAD

**Issue by fshuetli** [cybercase/netmd-js#31]
Dear Asivery

Many years ago I recorded my own concerts with a Sony Minidisc and then transferred the audio to a Windows PC (using the Software Sonic Stage) as *.OMG file.
What I did not know by then was, they I needed to save the key which was hidden and stored on the Windows PC.
Nowadays I can no longer play these files.
Are you planning to work on OMG-files as well?

**Comment by Invictaz** [comment]
@asivery

**Comment by asivery** [comment]
Hello @fshuetli, @Invictaz . From what I know these files can't be decrypted unless a Sony MZ-RH1 was used to download them to the computer. If that was the case, you can try running ffmpeg on them to decode them to WAVs. The command for this would be  `ffmpeg -i <your OMG file> <your WAV file>`. From then, you could use Web Minidisc to put them back on the disc or just leave them as WAV with no DRM. I have tested this with OMA files. Not sure OMGs will behave the same way, but it's worth giving it a try.
Let me know how it goes. Good luck!

**Comment by fshuetli** [comment]
Dear @asivery 

Thank you very much for your answer.
Unfortunately it does not work with ffmpeg. Actually that's what happens:

```
[oma @ 0x7ff54c800e00] Format oma detected only with low score of 1, misdetection possible!
[oma @ 0x7ff54c800e00] Couldn't find the EA3 header !
JAM.omg: Invalid data found when processing input
```
Source: https://stackoverflow.com/questions/59918433/convert-omg-with-ffmpeg (my post)

Would I help if I sent you an example *.OMG file?
(The device was not a Sony MZ-RH1. If I remember correctly it was Sony MZ-NH700 or similar.)

**Comment by fshuetli** [comment]
https://www.dropbox.com/s/bhozx2w1zmo82vz/JAM.omg?dl=0 as an example

**Comment by asivery** [comment]
@fshuetli I've looked at the file and wasn't able to decrypt it. I don't think it will be possible to recover the audio if you don't get the key back unfortunately.

**Comment by fshuetli** [comment]
@asivery thank's for checking. it's so sad that sony locked out all these customers from their own concert recordings...

**Comment by asivery** [comment]
@fshuetli No problem, sorry I wasn't able to help - very aggressive DRM is one of the reasons MD failed in the first place...

**Comment by fshuetli** [comment]
very sad - but thanks
