### ISSUE TITLE
Does ATRAC compression happen inside a Sony recorder?

### ISSUE THREAD

**Issue by aaronamm** [cybercase/netmd-js#32]
Hello everyone

I would like to make sure if ATRAC compression happens inside a Sony recorder?
Given this example:
I have uploaded a raw PCM with 16bit depth, 44100 Hz sampling frequency to a Net MD recorder with the following command.
```sh
netmdcli upload song.raw -f sp
```
I can play a song on a disc without any issues.
I am pretty sure an  ATRAC compression happens inside a Net MD recorder.
However, I would like you to confirm if a Net MD recorder does ATRAC compression and `netmdcli` does nothing about ATRAC compression.

why does the MD device require a 16bit/44.1khz input file for recording in SP mode?  If there is Net MD specification, I would be glad if you could show it to me.
FYI, I have uploaded a WAV file with 16bit depth, 44100 Hz to a Net MD recorder (bypassing Web MiniDisc) and it worked as well.

According to this question, if ATRAC compression happens inside a Sony recorder, will recording 1:1 with optical input produce the same result as Net MD recording?

Given this scenario:
- We use a recorder that supports both optical input recording and Net MD recording, e.g. Sony MDS-S500.
- We use a wav file 16bit depth, 44100 Hz as an input file for both two methods.
- We write the input file to a CD and use a CD player to get optical out for 1:1 optical input recording.
- We upload the input to a recorder with `netmdcli` and SP mode.

Are two ATRAC outputs on an MD identical or bit by bit match? If not,  will it be very different that we can detect by our ears?

Thank you so much.

**Comment by aaronamm** [comment]
CC @asivery @Invictaz

**Comment by asivery** [comment]
Hi @aaronamm !
1. ATRAC SP compressions indeed happens on the NetMD unit. LP2/4 compression happens before sending it to the device (on the computer). Web Minidisc uses [atracdenc](https://github.com/dcherednik/atracdenc) for that, but it's still a work in progress.
2. I don't know why the data required by the device has to be 16bit 44.1kHz, but my guess is that value comes from reverse engineering SonicStage / some other NetMD upload program. Maybe the you can find some more info on that in the linux-minidisc project netmd-js is based on.
3. If you record SP with the help of NetMD, the quality should be the same as if recorded via optical / coax - at least that's what I think is the case - in both cases the data is encoded by the unit. For LP that is certainly not the case - NetMD sends already encoded ATRAC3 signal to the device, but if you were to record via optical / coax the device would function as the encoder. There are some undocumented functionality that allows some devices to LP2/4 encode on-the-fly via NetMD but it's not supported by netmd-js. 
If you have any more questions, feel free to ask. Just remember I'm not an expert on the topic and these are just my thoughts. I haven't done any tests that confirm the sound is exactly the same. In my opinion though, even if the sound differed a bit in the case of SP, it would be impossible, or nearly impossible to hear.

**Comment by aaronamm** [comment]
Hello @asivery .
Thank you so much for your reply. Your answers are very clear and helpful. 
If I can find more information why SP recording requires 16bit 44.1kHz raw file,  I will share it with you.
Furthermore, thanks for your contribution to MD communities by maintaining Web MiniDisc which is such a wonderful project.

**Comment by aaronamm** [comment]
@asivery  got an answer from linux-minidisc team. Please check [GitHub issue - Why does an MD device require a 16bit/44.1khz input file for recording in SP mode?](https://github.com/linux-minidisc/linux-minidisc/issues/77#issuecomment-1048246746).

**Comment by asivery** [comment]
@aaronamm That's pretty much what I thought - just a value that Sony decided on when creating the standard. Thanks for letting me know.

**Comment by aaronamm** [comment]
@asivery  my pleasure.
